import { AAVE_CLAIM_A } from './AAVE-CLAIM-A'
import { AAVE_CLAIM_B } from './AAVE-CLAIM-B'
import { AAVE_STAKE_A } from './AAVE-STAKE-A'
import { AAVE_V1 } from './AAVE-V1-A'
import { AAVE_V2 } from './AAVE-V2-A'
import { AUTHORITY_A } from './AUTHORITY-A'
import { BASIC_A } from './BASIC-A'
import { COMP_A } from './COMP-A'
import { COMPOUND_A } from './COMPOUND-A'
import { MAKERDAO_A } from './MAKERDAO-A'
import { POLYGON_BRIDGE_A } from './POLYGON-BRIDGE-A'
import { UNISWAP_A } from './UNISWAP-A'
import { AAVE_V1_IMPORT_A } from './AAVE-V1-IMPORT-A'
import { AAVE_V2_IMPORT_A } from './AAVE-V2-IMPORT-A'
import { COMPOUND_IMPORT_A } from './COMPOUND-IMPORT-A'
import { INSTAPOOL_A } from './INSTAPOOL-A'
import { PARASWAP_A } from './PARASWAP-A'

import { AAVE_V2_IMPORT_B } from './AAVE-V2-IMPORT-B'
import { COMPOUND_IMPORT_B } from './COMPOUND-IMPORT-B'
import { MAKERDAO_CLAIM_A } from './MAKERDAO-CLAIM-A'
import { G_UNISWAP_A } from './G-UNISWAP-A'
import { STAKE_ERC20_A } from './STAKE-ERC20-A'
import { INST_STAKING_A } from './INST-STAKING-A'
import { WETH_A } from './WETH-A'
import { INST_A } from './INST-A'
import { REFINANCE_A } from './REFINANCE-A'
import { INST_LM_A } from './INST-LM-A'
import { UNISWAP_V2_A } from './UNISWAP-V2-A'
import { LIQUITY_A } from './LIQUITY-A'
import { REFLEXER_A } from './REFLEXER-A'
import { UNISWAP_V3_A } from './UNISWAP-V3-A'
import { B_COMPOUND_A } from './B-COMPOUND-A'
import { B_MAKERDAO_A } from './B-MAKERDAO-A'
import { B_LIQUITY_A } from './B-LIQUITY-A'
import { BASIC_B } from './BASIC-B'
import { BASIC_C } from './BASIC-C'
import { UNISWAP_V3_STAKE_A } from './UNISWAP-V3-STAKE-A'
import { YEARN_VAULT_A } from './YEARN-VAULT-A'
import { INST_STAKING_B } from './INST-STAKING-B'
import { GELATO_AAVE_A } from './GELATO-AAVE-A'
import { POOLTOGETHER_A } from './POOLTOGETHER-A'
import { INSTAPOOL_B } from './INSTAPOOL-B'
import { BENQI_A } from './BENQI-A'
import { QI_A } from './QI-A'
import { COMPOUND_IMPORT_C } from './COMPOUND-IMPORT-C'
import { AAVE_V2_IMPORT_C } from './AAVE-V2-IMPORT-C'
import { UNISWAP_SELL_BETA } from './UNISWAP-SELL-BETA'

import { INTEROP_A } from './INTEROP-A'
import { INTEROP_STAGING_A } from './INTEROP-STAGING-A'
import { INSTAPOOL_C } from './INSTAPOOL-C'

import { UNIVERSE_A } from './UNIVERSE-A'
import { WAVAX_A } from './WAVAX-A'
import { WMATIC_A } from './WMATIC-A'
import { WFTM_A } from './WFTM-A'
import { QUICKSWAP_A } from './QUICKSWAP-A'
import { ONEINCH_A } from './1INCH-A'
import { ONEINCH_B } from './1INCH-B'
import { ONEINCH_V3_A } from './1INCH-V3-A'
import { ONEINCH_V4_A } from './1INCH-V4-A'
import { PARASWAP_V5_A } from './PARASWAP-V5-A'
import { ZEROX_A } from './ZEROX-A'
import { ZEROX_V4_A } from './ZEROX-V4-A'
import { UNISWAP_V3_ROUTER_A } from './UNISWAP-V3-ROUTER-A'
import { SUSHISWAP_A } from './SUSHISWAP-A'
import { UBIQUITY_A } from './UBIQUITY-A'
import { UNISWAP_V3_STAKER_B } from './UNISWAP-V3-STAKER-B'
import { PANGOLIN_A } from './PANGOLIN-A'
import { PANGOLIN_STAKE_A } from './PANGOLIN-STAKE-A'
import { MSTABLE_A } from './MSTABLE-A'
import { LIDO_STETH_A } from './LIDO-STETH-A'
import { AAVE_V3_A } from './AAVE-V3-A'
import { AAVE_IMPORT_V2_V3_A } from './AAVE-IMPORT-V2-V3-A'
import { AAVE_V3_IMPORT_A } from './AAVE-V3-IMPORT-A'
import { COMPOUND_IMPORT_D } from './COMPOUND-IMPORT-D'
import { LITE_A } from './LITE-A'
import { AAVE_V3_IMPORT_PERMIT_A } from './AAVE-V3-IMPORT-PERMIT-A'
import { HOP_A } from './HOP-A'
import { AAVE_V3_CLAIM_A } from './AAVE-V3-CLAIM-A'
import { NOTIONAL_V2_A } from './NOTIONAL-V2-A'
import { HOP_MAINNET_A } from './HOP-MAINNET-A'
import { UNISWAP_V3_SWAP_A } from './UNISWAP-V3-SWAP-A'
import { SWAP_AGGREGATOR_A } from './SWAP-AGGREGATOR-A'
import { INSTA_DEX_SIMULATION_A } from './INSTA-DEX-SIMULATION-A'
import { DSA_SPELL_A } from './DSA-SPELL-A'
import { SOCKET_A } from './SOCKET-A'
import { AAVE_V3_AUTOMATION_A } from './AAVE-V3-AUTOMATION-A'
import { AAVE_V3_AUTOMATION_STAGING_A } from './AAVE-V3-AUTOMATION-STAGING-A'
import { EULER_A } from './EULER-A'
import { EULER_IMPORT_A } from './EULER-IMPORT-A'
import { EULER_REWARDS_A } from './EULER-REWARDS-A'
import { AAVE_V2_AUTOMATION_STAGING_A } from './AAVE-V2-AUTOMATION-STAGING-A'
import { AAVE_V2_AUTOMATION_A } from './AAVE-V2-AUTOMATION-A'
import { COMPOUND_V3_A } from './COMPOUND-V3-A'
import { WSTETH_A } from './WSTETH-A'
import { COMPOUND_V3_REWARDS_A } from './COMPOUND-V3-REWARDS-A'
import { LITE_B } from './LITE-B'
import { MORPHO_AAVE_V2_A } from './MORPHO-AAVE-V2-A'
import { MORPHO_AAVE_V3_A } from './MORPHO-AAVE-V3-A'
import { MORPHO_COMPOUND_V2_A } from './MORPHO-COMPOUND-V2-A'
import { MORPHO_REWARDS_A } from './MORPHO-REWARDS-A'
import { ONEINCH_V5_A } from './1INCH-V5-A'
import { AVO_APPROVE_A } from './AVO-APPROVE-A'
import { AVO_APPROVE_STAGING_A } from './AVO-APPROVE-STAGING-A'
import { AVO_MAKER_A } from './AVO-MAKER-A'
import { AVO_MAKER_STAGING_A } from './AVO-MAKER-STAGING-A'
import { ARB_CLAIM_A } from './ARB-CLAIM-A'
import { CONNEXT_A } from './CONNEXT-A'
import { SPARK_A } from './SPARK-A'
import { KYBER_AGGREGATOR_A } from './KYBER-AGGREGATOR-A'
import { BASIC_D } from './BASIC-D'
import { AVO_APPROVE_MULTISIG_A } from './AVO-APPROVE-MULTISIG-A'
import { AVO_APPROVE_MULTISIG_STAGING_A } from './AVO-APPROVE-MULTISIG-STAGING-A'
import { CRV_USD_A } from './CRV-USD-A'

export const connectorsV2_M1 = {
  'MORPHO-REWARDS-A': MORPHO_REWARDS_A,
  'LITE-B': LITE_B,
  'MORPHO-AAVE-V2-A': MORPHO_AAVE_V2_A,
  'MORPHO-AAVE-V3-A': MORPHO_AAVE_V3_A,
  'MORPHO-COMPOUND-V2-A': MORPHO_COMPOUND_V2_A,
  'COMPOUND-V3-REWARDS-A': COMPOUND_V3_REWARDS_A,
  'COMPOUND-V3-A': COMPOUND_V3_A,
  'AAVE-V2-AUTOMATION-A': AAVE_V2_AUTOMATION_A,
  'AAVE-V2-AUTOMATION-STAGING-A': AAVE_V2_AUTOMATION_STAGING_A,
  'EULER-A': EULER_A,
  'EULER-IMPORT-A': EULER_IMPORT_A,
  'EULER-REWARDS-A': EULER_REWARDS_A,
  'AAVE-V3-AUTOMATION-STAGING-A': AAVE_V3_AUTOMATION_STAGING_A,
  'AAVE-V3-AUTOMATION-A': AAVE_V3_AUTOMATION_A,
  'SOCKET-A': SOCKET_A,
  'DSA-SPELL-A': DSA_SPELL_A,
  'INSTA-DEX-SIMULATION-A': INSTA_DEX_SIMULATION_A,
  'SWAP-AGGREGATOR-A': SWAP_AGGREGATOR_A,
  'UNISWAP-V3-SWAP-A': UNISWAP_V3_SWAP_A,
  'HOP-MAINNET-A': HOP_MAINNET_A,
  'NOTIONAL-V2-A': NOTIONAL_V2_A,
  'AAVE-V3-CLAIM-A': AAVE_V3_CLAIM_A,
  'HOP-A': HOP_A,
  'AAVE-V3-IMPORT-PERMIT-A': AAVE_V3_IMPORT_PERMIT_A,
  'LITE-A': LITE_A,
  'COMPOUND-IMPORT-D': COMPOUND_IMPORT_D,
  'AAVE-V3-IMPORT-A': AAVE_V3_IMPORT_A,
  'AAVE-IMPORT-V2-V3-A': AAVE_IMPORT_V2_V3_A,
  'AAVE-V3-A': AAVE_V3_A,
  'WFTM-A': WFTM_A,
  'MSTABLE-A': MSTABLE_A,
  'LIDO-STETH-A': LIDO_STETH_A,
  'PANGOLIN-STAKE-A': PANGOLIN_STAKE_A,
  'PANGOLIN-A': PANGOLIN_A,
  'UNISWAP-V3-STAKER-B': UNISWAP_V3_STAKER_B,
  'UNISWAP-V3-ROUTER-A': UNISWAP_V3_ROUTER_A,
  'SUSHISWAP-A': SUSHISWAP_A,
  'ZEROX-V4-A': ZEROX_V4_A,
  'ZEROX-A': ZEROX_A,
  'PARASWAP-V5-A': PARASWAP_V5_A,
  '1INCH-A': ONEINCH_A,
  '1INCH-B': ONEINCH_B,
  '1INCH-V3-A': ONEINCH_V3_A,
  '1INCH-V4-A': ONEINCH_V4_A,
  '1INCH-V5-A': ONEINCH_V5_A,
  'QUICKSWAP-A': QUICKSWAP_A,
  'INSTAPOOL-C': INSTAPOOL_C,
  'UNISWAP-SELL-BETA': UNISWAP_SELL_BETA,
  'AAVE-V2-IMPORT-C': AAVE_V2_IMPORT_C,
  'COMPOUND-IMPORT-C': COMPOUND_IMPORT_C,
  'QI-A': QI_A,
  'BENQI-A': BENQI_A,
  'INSTAPOOL-B': INSTAPOOL_B,
  'POOLTOGETHER-A': POOLTOGETHER_A,
  'GELATO-AAVE-A': GELATO_AAVE_A,
  'INST-STAKING-B': INST_STAKING_B,
  'YEARN-VAULT-A': YEARN_VAULT_A,
  'UNISWAP-V3-STAKE-A': UNISWAP_V3_STAKE_A,
  'BASIC-C': BASIC_C,
  'BASIC-B': BASIC_B,
  'B-LIQUITY-A': B_LIQUITY_A,
  'B-MAKERDAO-A': B_MAKERDAO_A,
  'B-COMPOUND-A': B_COMPOUND_A,
  'UNISWAP-V3-A': UNISWAP_V3_A,
  'REFLEXER-A': REFLEXER_A,
  'LIQUITY-A': LIQUITY_A,
  'UNISWAP-V2-A': UNISWAP_V2_A,
  'INST-LM-A': INST_LM_A,
  'REFINANCE-A': REFINANCE_A,
  'INST-A': INST_A,
  'WETH-A': WETH_A,
  'WSTETH-A': WSTETH_A,
  'INST-STAKING-A': INST_STAKING_A,
  'STAKE-ERC20-A': STAKE_ERC20_A,
  'G-UNISWAP-A': G_UNISWAP_A,
  'INSTAPOOL-A': INSTAPOOL_A,
  'COMPOUND-IMPORT-A': COMPOUND_IMPORT_A,
  'AAVE-V2-IMPORT-A': AAVE_V2_IMPORT_A,
  'AAVE-V1-IMPORT-A': AAVE_V1_IMPORT_A,
  'AAVE-CLAIM-A': AAVE_CLAIM_A,
  'AAVE-CLAIM-B': AAVE_CLAIM_B,
  'AAVE-V1-A': AAVE_V1,
  'AAVE-V2-A': AAVE_V2,
  'AUTHORITY-A': AUTHORITY_A,
  'BASIC-A': BASIC_A,
  'COMP-A': COMP_A,
  'COMPOUND-A': COMPOUND_A,
  'MAKERDAO-A': MAKERDAO_A,
  'UNISWAP-A': UNISWAP_A,
  'POLYGON-BRIDGE-A': POLYGON_BRIDGE_A,
  'AAVE-STAKE-A': AAVE_STAKE_A,
  'PARASWAP-A': PARASWAP_A,
  'COMPOUND-IMPORT-B': COMPOUND_IMPORT_B,
  'AAVE-V2-IMPORT-B': AAVE_V2_IMPORT_B,
  'MAKERDAO-CLAIM-A': MAKERDAO_CLAIM_A,
  'INTEROP-A': INTEROP_A,
  'INTEROP-STAGING-A': INTEROP_STAGING_A,
  'WMATIC-A': WMATIC_A,
  'WAVAX-A': WAVAX_A,
  'UNIVERSE-A': UNIVERSE_A,
  'UBIQUITY-A': UBIQUITY_A,
  'AVO-APPROVE-A': AVO_APPROVE_A,
  'AVO-APPROVE-STAGING-A': AVO_APPROVE_STAGING_A,
  'AVO-MAKER-A': AVO_MAKER_A,
  'AVO-MAKER-STAGING-A': AVO_MAKER_STAGING_A,
  'ARB-CLAIM-A': ARB_CLAIM_A,
  'CONNEXT-A': CONNEXT_A,
  'SPARK-A': SPARK_A,
  'KYBER-AGGREGATOR-A': KYBER_AGGREGATOR_A,
  'BASIC-D': BASIC_D,
  'AVO-APPROVE-MULTISIG-A': AVO_APPROVE_MULTISIG_A,
  'AVO-APPROVE-MULTISIG-STAGING-A': AVO_APPROVE_MULTISIG_STAGING_A,
  'CURVE-USD-A': CRV_USD_A,
}
