import {ONEINCH_A} from './1INCH-A'
import {AAVE_CLAIM_A} from './AAVE-CLAIM-A'
import {AAVE_CLAIM_B} from './AAVE-CLAIM-B'
import {AAVE_STAKE_A} from './AAVE-STAKE-A'
import {AAVE_V1} from './AAVE-V1-A'
import {AAVE_V2} from './AAVE-V2-A'
import {AUTHORITY_A} from './AUTHORITY-A'
import {BASIC_A} from './BASIC-A'
import {COMP_A} from './COMP-A'
import {COMPOUND_A} from './COMPOUND-A'
import {MAKERDAO_A} from './MAKERDAO-A'
import {POLYGON_BRIDGE_A} from './POLYGON-BRIDGE-A'
import {UNISWAP_A} from './UNISWAP-A'
import {AAVE_V1_IMPORT_A} from './AAVE-V1-IMPORT-A'
import {AAVE_V2_IMPORT_A} from './AAVE-V2-IMPORT-A'
import {COMPOUND_IMPORT_A} from './COMPOUND-IMPORT-A'
import {INSTAPOOL_A} from './INSTAPOOL-A'
import {PARASWAP_A} from './PARASWAP-A'

import {AAVE_V2_IMPORT_B} from './AAVE-V2-IMPORT-B'
import {COMPOUND_IMPORT_B} from './COMPOUND-IMPORT-B'
import {MAKERDAO_CLAIM_A} from './MAKERDAO-CLAIM-A'
import {G_UNISWAP_A} from './G-UNISWAP-A'
import {STAKE_ERC20_A} from './STAKE-ERC20-A'
import {INST_STAKING_A} from './INST-STAKING-A'
import {ONEINCH_B} from './1INCH-B'
export const connectorsV2_M1 =  {
    "1INCH-B": ONEINCH_B,
    "INST-STAKING-A": INST_STAKING_A,
    "STAKE-ERC20-A": STAKE_ERC20_A,
    "G-UNISWAP-A": G_UNISWAP_A,
    "INSTAPOOL-A": INSTAPOOL_A,
    "COMPOUND-IMPORT-A": COMPOUND_IMPORT_A,
    "AAVE-V2-IMPORT-A": AAVE_V2_IMPORT_A,
    "AAVE-V1-IMPORT-A": AAVE_V1_IMPORT_A,
    "1INCH-A": ONEINCH_A,
    "AAVE-CLAIM-A": AAVE_CLAIM_A,
    "AAVE-CLAIM-B": AAVE_CLAIM_B,
    "AAVE-V1-A": AAVE_V1,
    "AAVE-V2-A": AAVE_V2,
    "AUTHORITY-A": AUTHORITY_A,
    "BASIC-A": BASIC_A,
    "COMP-A": COMP_A,
    "COMPOUND-A": COMPOUND_A,
    "MAKERDAO-A": MAKERDAO_A,
    "UNISWAP-A": UNISWAP_A,
    "POLYGON-BRIDGE-A": POLYGON_BRIDGE_A,
    "AAVE-STAKE-A": AAVE_STAKE_A,
    "PARASWAP-A": PARASWAP_A,
    "COMPOUND-IMPORT-B": COMPOUND_IMPORT_B,
    "AAVE-V2-IMPORT-B": AAVE_V2_IMPORT_B,
    "MAKERDAO-CLAIM-A": MAKERDAO_CLAIM_A,
}
