import {ONEINCH_A} from './1INCH-A'
import {AAVE_CLAIM_A} from './AAVE-CLAIM-A'
import {AAVE_CLAIM_B} from './AAVE-CLAIM-B'
import {AAVE_STAKE_A} from './AAVE-STAKE-A'
import {AAVE_V1} from './AAVE-V1-A'
import {AAVE_V2} from './AAVE-V2-A'
import {AUTHORITY_A} from './AUTHORITY-A'
import {BASIC_A} from './BASIC-A'
import {COMP_A} from './COMP-A'
import {COMPOUND_A} from './COMPOUND-A'
import {MAKERDAO_A} from './MAKERDAO-A'
import {POLYGON_BRIDGE_A} from './POLYGON-BRIDGE-A'
import {UNISWAP_A} from './UNISWAP-A'
import {AAVE_V1_IMPORT_A} from './AAVE-V1-IMPORT-A'
import {AAVE_V2_IMPORT_A} from './AAVE-V2-IMPORT-A'
import {COMPOUND_IMPORT_A} from './COMPOUND-IMPORT-A'
import {INSTAPOOL_A} from './INSTAPOOL-A'
import {PARASWAP_A} from './PARASWAP-A'

import {AAVE_V2_IMPORT_B} from './AAVE-V2-IMPORT-B'
import {COMPOUND_IMPORT_B} from './COMPOUND-IMPORT-B'
import {MAKERDAO_CLAIM_A} from './MAKERDAO-CLAIM-A'
import {G_UNISWAP_A} from './G-UNISWAP-A'
import {STAKE_ERC20_A} from './STAKE-ERC20-A'
import {INST_STAKING_A} from './INST-STAKING-A'
import {ONEINCH_B} from './1INCH-B'
import {WETH_A} from './WETH-A'
import {INST_A} from './INST-A'
import {REFINANCE_A} from './REFINANCE-A'
import {INST_LM_A} from './INST-LM-A'
import {UNISWAP_V2_A} from './UNISWAP-V2-A'
import {LIQUITY_A} from './LIQUITY-A'
import {REFLEXER_A} from './REFLEXER-A'
import {UNISWAP_V3_A} from './UNISWAP-V3-A'
import {B_COMPOUND_A} from './B-COMPOUND-A'
import {B_MAKERDAO_A} from './B-MAKERDAO-A'
import {B_LIQUITY_A} from './B-LIQUITY-A'
import {BASIC_B} from './BASIC-B'
import {BASIC_C} from './BASIC-C'
import {UNISWAP_V3_STAKE_A} from './UNISWAP-V3-STAKE-A'
import {YEARN_VAULT_A} from './YEARN-VAULT-A'
import {INST_STAKING_B} from './INST-STAKING-B'
import {GELATO_AAVE_A} from './GELATO-AAVE-A'
import {POOLTOGETHER_A} from './POOLTOGETHER-A'
import {INSTAPOOL_B} from './INSTAPOOL-B'
import {BENQI_A} from './BENQI-A'
import {QI_A} from './QI-A'
import {COMPOUND_IMPORT_C} from './COMPOUND-IMPORT-C'
import {AAVE_V2_IMPORT_C} from './AAVE-V2-IMPORT-C'
import {UNISWAP_SELL_BETA} from './UNISWAP-SELL-BETA'

import {INTEROP_A} from './INTEROP-A'
import {INTEROP_STAGING_A} from './INTEROP-STAGING-A'
import {INSTAPOOL_C} from './INSTAPOOL-C'

import {WAVAX_A} from './WAVAX-A'
import {WMATIC_A} from './WMATIC-A'
import {QUICKSWAP_A} from './QUICKSWAP-A'
export const connectorsV2_M1 =  {
    "QUICKSWAP-A": QUICKSWAP_A,
    "INSTAPOOL-C": INSTAPOOL_C,
    "UNISWAP-SELL-BETA": UNISWAP_SELL_BETA,
    "AAVE-V2-IMPORT-C": AAVE_V2_IMPORT_C,
    "COMPOUND-IMPORT-C": COMPOUND_IMPORT_C,
    "QI-A": QI_A,
    "BENQI-A": BENQI_A,
    "INSTAPOOL-B": INSTAPOOL_B,
    "POOLTOGETHER-A": POOLTOGETHER_A,
    "GELATO-AAVE-A": GELATO_AAVE_A,
    "INST-STAKING-B": INST_STAKING_B,
    "YEARN-VAULT-A": YEARN_VAULT_A,
    "UNISWAP-V3-STAKE-A": UNISWAP_V3_STAKE_A,
    "BASIC-C": BASIC_C,
    "BASIC-B": BASIC_B,
    "B-LIQUITY-A": B_LIQUITY_A,
    "B-MAKERDAO-A": B_MAKERDAO_A,
    "B-COMPOUND-A": B_COMPOUND_A,
    "UNISWAP-V3-A": UNISWAP_V3_A,
    "REFLEXER-A": REFLEXER_A,
    "LIQUITY-A": LIQUITY_A,
    "UNISWAP-V2-A": UNISWAP_V2_A,
    "INST-LM-A": INST_LM_A,
    "REFINANCE-A": REFINANCE_A,
    "INST-A": INST_A,
    "WETH-A": WETH_A,
    "1INCH-B": ONEINCH_B,
    "INST-STAKING-A": INST_STAKING_A,
    "STAKE-ERC20-A": STAKE_ERC20_A,
    "G-UNISWAP-A": G_UNISWAP_A,
    "INSTAPOOL-A": INSTAPOOL_A,
    "COMPOUND-IMPORT-A": COMPOUND_IMPORT_A,
    "AAVE-V2-IMPORT-A": AAVE_V2_IMPORT_A,
    "AAVE-V1-IMPORT-A": AAVE_V1_IMPORT_A,
    "1INCH-A": ONEINCH_A,
    "AAVE-CLAIM-A": AAVE_CLAIM_A,
    "AAVE-CLAIM-B": AAVE_CLAIM_B,
    "AAVE-V1-A": AAVE_V1,
    "AAVE-V2-A": AAVE_V2,
    "AUTHORITY-A": AUTHORITY_A,
    "BASIC-A": BASIC_A,
    "COMP-A": COMP_A,
    "COMPOUND-A": COMPOUND_A,
    "MAKERDAO-A": MAKERDAO_A,
    "UNISWAP-A": UNISWAP_A,
    "POLYGON-BRIDGE-A": POLYGON_BRIDGE_A,
    "AAVE-STAKE-A": AAVE_STAKE_A,
    "PARASWAP-A": PARASWAP_A,
    "COMPOUND-IMPORT-B": COMPOUND_IMPORT_B,
    "AAVE-V2-IMPORT-B": AAVE_V2_IMPORT_B,
    "MAKERDAO-CLAIM-A": MAKERDAO_CLAIM_A,
    "INTEROP-A": INTEROP_A,
    "INTEROP-STAGING-A": INTEROP_STAGING_A,
    "WMATIC-A": WMATIC_A,
    "WAVAX-A": WAVAX_A
}
