import { AbiItem } from 'web3-utils'

export const NOTIONAL_V2_A: AbiItem[] = [
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'account', type: 'address' }],
    name: 'LogBatchActionRaw',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'notesClaimed', type: 'uint256' },
    ],
    name: 'LogClaimNOTE',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'bool', name: 'isUnderlying', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { indexed: false, internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { indexed: false, internalType: 'uint32', name: 'minLendRate', type: 'uint32' },
    ],
    name: 'LogDepositAndLend',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'bool', name: 'isUnderlying', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { indexed: false, internalType: 'int256', name: 'nTokenBalanceChange', type: 'int256' },
    ],
    name: 'LogDepositAndMintNToken',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'bool', name: 'isUnderlying', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'assetCashDeposited', type: 'uint256' },
    ],
    name: 'LogDepositCollateral',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'useUnderlying', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint16', name: 'borrowCurrencyId', type: 'uint16' },
      { indexed: false, internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { indexed: false, internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { indexed: false, internalType: 'uint32', name: 'maxBorrowRate', type: 'uint32' },
      { indexed: false, internalType: 'bool', name: 'redeemToUnderlying', type: 'bool' },
    ],
    name: 'LogDepositCollateralBorrowAndWithdraw',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'uint256', name: 'cashBalanceToMint', type: 'uint256' },
      { indexed: false, internalType: 'int256', name: 'nTokenBalanceChange', type: 'int256' },
    ],
    name: 'LogMintNTokenFromCash',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'bptAmount', type: 'uint256' },
    ],
    name: 'LogMintSNoteFromBPT',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'noteAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'ethAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'minBPT', type: 'uint256' },
    ],
    name: 'LogMintSNoteFromETH',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'noteAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'wethAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'minBPT', type: 'uint256' },
    ],
    name: 'LogMintSNoteFromWETH',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'uint96', name: 'tokensToRedeem', type: 'uint96' },
      { indexed: false, internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { indexed: false, internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
    ],
    name: 'LogRedeemNTokenAndDeleverage',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'bool', name: 'sellTokenAssets', type: 'bool' },
      { indexed: false, internalType: 'uint96', name: 'tokensToRedeem', type: 'uint96' },
      { indexed: false, internalType: 'int256', name: 'assetCashChange', type: 'int256' },
    ],
    name: 'LogRedeemNTokenRaw',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'uint96', name: 'tokensToRedeem', type: 'uint96' },
      { indexed: false, internalType: 'uint256', name: 'amountToWithdraw', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'redeemToUnderlying', type: 'bool' },
    ],
    name: 'LogRedeemNTokenWithdraw',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'sNOTEAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'minWETH', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'minNOTE', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'redeemWETH', type: 'bool' },
    ],
    name: 'LogRedeemSNote',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'account', type: 'address' }],
    name: 'LogStartCoolDown',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'account', type: 'address' }],
    name: 'LogStopCoolDown',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'bool', name: 'isUnderlying', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'amountWithdrawn', type: 'uint256' },
    ],
    name: 'LogWithdrawCollateral',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { indexed: false, internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { indexed: false, internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { indexed: false, internalType: 'uint32', name: 'maxBorrowRate', type: 'uint32' },
    ],
    name: 'LogWithdrawLend',
    type: 'event',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'enum DepositActionType', name: 'actionType', type: 'uint8' },
          { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
          { internalType: 'uint256', name: 'depositActionAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'withdrawAmountInternalPrecision', type: 'uint256' },
          { internalType: 'bool', name: 'withdrawEntireCashBalance', type: 'bool' },
          { internalType: 'bool', name: 'redeemToUnderlying', type: 'bool' },
          { internalType: 'bytes32[]', name: 'trades', type: 'bytes32[]' },
        ],
        internalType: 'struct BalanceActionWithTrades[]',
        name: 'actions',
        type: 'tuple[]',
      },
    ],
    name: 'batchActionRaw',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'setId', type: 'uint256' }],
    name: 'claimNOTE',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { internalType: 'bool', name: 'useUnderlying', type: 'bool' },
      { internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { internalType: 'uint32', name: 'minLendRate', type: 'uint32' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
    ],
    name: 'depositAndLend',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { internalType: 'bool', name: 'useUnderlying', type: 'bool' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'depositAndMintNToken',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'bool', name: 'useUnderlying', type: 'bool' },
      { internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'depositCollateral',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'depositCurrencyId', type: 'uint16' },
      { internalType: 'enum DepositActionType', name: 'depositAction', type: 'uint8' },
      { internalType: 'uint256', name: 'depositAmount', type: 'uint256' },
      { internalType: 'uint16', name: 'borrowCurrencyId', type: 'uint16' },
      { internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { internalType: 'uint32', name: 'maxBorrowRate', type: 'uint32' },
      { internalType: 'bool', name: 'redeemToUnderlying', type: 'bool' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'depositCollateralBorrowAndWithdraw',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'uint256', name: 'cashBalanceToMint', type: 'uint256' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'mintNTokenFromCash',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bptAmount', type: 'uint256' }],
    name: 'mintSNoteFromBPT',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'noteAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'ethAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'minBPT', type: 'uint256' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
    ],
    name: 'mintSNoteFromETH',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'noteAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'wethAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'minBPT', type: 'uint256' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
    ],
    name: 'mintSNoteFromWETH',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'uint96', name: 'tokensToRedeem', type: 'uint96' },
      { internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { internalType: 'uint32', name: 'minLendRate', type: 'uint32' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
    ],
    name: 'redeemNTokenAndDeleverage',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'uint96', name: 'tokensToRedeem', type: 'uint96' },
      { internalType: 'uint256', name: 'amountToWithdraw', type: 'uint256' },
      { internalType: 'bool', name: 'redeemToUnderlying', type: 'bool' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'redeemNTokenAndWithdraw',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'bool', name: 'sellTokenAssets', type: 'bool' },
      { internalType: 'uint96', name: 'tokensToRedeem', type: 'uint96' },
      { internalType: 'bool', name: 'acceptResidualAssets', type: 'bool' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'redeemNTokenRaw',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sNOTEAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'minWETH', type: 'uint256' },
      { internalType: 'uint256', name: 'minNOTE', type: 'uint256' },
      { internalType: 'bool', name: 'redeemWETH', type: 'bool' },
    ],
    name: 'redeemSNote',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'startCoolDown',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stopCoolDown',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'bool', name: 'redeemToUnderlying', type: 'bool' },
      { internalType: 'uint256', name: 'withdrawAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'getId', type: 'uint256' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'withdrawCollateral',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'currencyId', type: 'uint16' },
      { internalType: 'uint8', name: 'marketIndex', type: 'uint8' },
      { internalType: 'uint88', name: 'fCashAmount', type: 'uint88' },
      { internalType: 'uint32', name: 'maxBorrowRate', type: 'uint32' },
      { internalType: 'uint256', name: 'setId', type: 'uint256' },
    ],
    name: 'withdrawLend',
    outputs: [
      { internalType: 'string', name: '_eventName', type: 'string' },
      { internalType: 'bytes', name: '_eventParam', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
]
